#!/bin/sh
#
#
# Pull before committing
# Credential handling options:
#  - hardcode credentials in URL 
#  - use ssh with key auth 
#  - https://git-scm.com/docs/git-credential-store
#  - git credential helper on windows

# Redirect output to stderr, uncomment for more output for debugging
# exec 1>&2

# Leaves dangling commits because the pre-commit already has
# the HEAD hash in memory so a pull results in commit happening
# against a non-existent HEAD
git gc --prune=now --quiet

output=$(git pull --no-rebase)

# Handle non error output as otherwise it gets shown with any exit code by logseq
if [ "$output" = "Already up to date." ]; then
   # no ouput
   exit 0
else 
   # probably error print it to screen   
   echo "${output}"
fi

git add -A
